language: go

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - "1.10.x"
  - master

matrix:
  # Build OK if fails on unstable development versions of Go.
  allow_failures:
    - go: master
  # Don't wait for tests to finish on allow_failures.
  # Mark the build finished if tests pass on other versions of Go.
  fast_finish: true

go_import_path: firebase.google.com/go

before_install:
    - go get github.com/golang/lint/golint # Golint requires Go 1.6 or later.

install:
    # Prior to golang 1.8, this can trigger an error for packages containing only tests.
    - go get -t -v $(go list ./... | grep -v integration)

script:
    - golint -set_exit_status $(go list ./...)
    - ./.travis.gofmt.sh
    - go test -v -race -test.short ./...        # Run tests with the race detector.
    - go vet -v ./...                           # Run Go static analyzer.
